=== masterofeye2021/xml2OH/SmartHomeDefinitionV2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2024 rel. 2 sp1 (x64) (https://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:altova="http://www.altova.com/xml-schema-extensions" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:attribute name="type">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="Switch"/>
				<xs:enumeration value="Number"/>
				<xs:enumeration value="Rollershutter"/>
				<xs:enumeration value="Contact"/>
				<xs:enumeration value="DateTime"/>
				<xs:enumeration value="String"/>
				<xs:enumeration value="Dimmer"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:element name="openhab">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="devices" type="devices"/>
				<xs:element name="groups" type="groups"/>
				<xs:element ref="knx.configuration"/>
				<xs:element ref="ical.configuration"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="devices">
		<xs:sequence>
			<xs:element name="device" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="device"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="device">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="channel">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="channel"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="device.area" type="area" use="required"/>
		<xs:attribute name="device.function">
			<xs:annotation>
				<xs:appinfo>
					<altova:exampleValues>
						<altova:example value="LIGHT"/>
					</altova:exampleValues>
				</xs:appinfo>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="function"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="device.comm.type" type="comm" default="KNX"/>
		<xs:attribute name="device.label" type="xs:string" use="required"/>
		<xs:attribute name="device.name" type="xs:string" use="required"/>
		<xs:attribute name="device.specification" use="required">
			<xs:simpleType>
				<xs:restriction base="device.specification">
					<xs:enumeration value="SteinelTruePräsenz"/>
					<xs:enumeration value="RolladenMDTKNX"/>
					<xs:enumeration value="ICALBinding"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="function">
		<xs:restriction base="xs:anyURI">
			<xs:enumeration value="LIGHT"/>
			<xs:enumeration value="SHUTTER"/>
			<xs:enumeration value="SENSOR"/>
			<xs:enumeration value="PINGDEVICE"/>
			<xs:enumeration value="CALENDAR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="unit">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ND"/>
			<xs:enumeration value="°C"/>
			<xs:enumeration value="K"/>
			<xs:enumeration value="U"/>
			<xs:enumeration value="I"/>
			<xs:enumeration value="%"/>
			<xs:enumeration value="ppm"/>
			<xs:enumeration value="hPa"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="channel">
		<xs:all>
			<xs:element name="link" type="xs:string"/>
			<xs:element name="connection">
				<xs:complexType>
					<xs:choice>
						<xs:element name="knx" type="knx"/>
						<xs:element name="ping" type="ping"/>
						<xs:element name="modbus" type="modbus"/>
						<xs:element ref="ical"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="groups">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="group.ref">
							<xs:complexType>
								<xs:attribute name="refid" type="xs:IDREF"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="alexa" type="alexa" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="format" type="format" use="required"/>
		<xs:attribute name="unit" type="unit" use="required"/>
		<xs:attribute name="access" type="access" use="required"/>
		<xs:attribute name="icon" use="required">
			<xs:simpleType>
				<xs:restriction base="icon"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="enable" type="xs:boolean" use="required"/>
		<xs:attribute name="persistence" type="xs:boolean" use="required"/>
		<xs:attribute name="label" type="xs:string" use="required"/>
		<xs:attribute ref="type" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="extention" type="xs:string" use="optional"/>
		<xs:attribute name="channel.id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:simpleType name="access">
		<xs:restriction base="xs:anyURI">
			<xs:enumeration value="R"/>
			<xs:enumeration value="RW"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="area">
		<xs:restriction base="xs:anyURI">
			<xs:enumeration value="WOZ"/>
			<xs:enumeration value="KUE"/>
			<xs:enumeration value="HWR"/>
			<xs:enumeration value="GWC"/>
			<xs:enumeration value="FLUEG"/>
			<xs:enumeration value="BUR"/>
			<xs:enumeration value="SLZ"/>
			<xs:enumeration value="BAD"/>
			<xs:enumeration value="KIZ"/>
			<xs:enumeration value="FLUDG"/>
			<xs:enumeration value="DCH"/>
			<xs:enumeration value="TKR"/>
			<xs:enumeration value="FLUKL"/>
			<xs:enumeration value="LAG"/>
			<xs:enumeration value="GAR"/>
			<xs:enumeration value="CAR"/>
			<xs:enumeration value=""/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="icon">
		<xs:restriction base="xs:anyURI">
			<xs:enumeration value="fa-lightbulb"/>
			<xs:enumeration value="fa-blinds"/>
			<xs:enumeration value="fa-radar"/>
			<xs:enumeration value="fa-temperature-three-quarters"/>
			<xs:enumeration value="fa-cloud"/>
			<xs:enumeration value="fa-droplet"/>
			<xs:enumeration value="fa-signal"/>
			<xs:enumeration value="fa-octagon"/>
			<xs:enumeration value="fa-lock"/>
			<xs:enumeration value="fa-arrows-up-down"/>
			<xs:enumeration value="fa-hand"/>
			<xs:enumeration value="fa-compass"/>
			<xs:enumeration value="fa-location-dot"/>
			<xs:enumeration value="fa-up-to-line"/>
			<xs:enumeration value="fa-down-from-line"/>
			<xs:enumeration value="fa-stethoscope"/>
			<xs:enumeration value="fa-droplet-percent"/>
			<xs:enumeration value="fa-wind"/>
			<xs:enumeration value="fa-poo"/>
			<xs:enumeration value="fa-heat"/>
			<xs:enumeration value="fa-calendar-day"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="comm">
		<xs:restriction base="xs:anyURI">
			<xs:enumeration value="KNX"/>
			<xs:enumeration value="MODBUS"/>
			<xs:enumeration value="PING"/>
			<xs:enumeration value="ICAL"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="knx">
		<xs:all>
			<xs:element name="add1" type="knx.address"/>
			<xs:element name="add2" type="knx.address"/>
			<xs:element name="add3" type="knx.address"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="knx.address">
		<xs:all>
			<xs:element name="main.ga">
				<xs:complexType>
					<xs:all>
						<xs:element name="main" type="xs:short"/>
						<xs:element name="middle" type="xs:short"/>
						<xs:element name="sub" type="xs:short"/>
					</xs:all>
					<xs:attribute name="is.readable" type="xs:boolean" default="false"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="listening.ga" minOccurs="0">
				<xs:complexType>
					<xs:all>
						<xs:element name="main" type="xs:short"/>
						<xs:element name="middle" type="xs:short"/>
						<xs:element name="sub" type="xs:short"/>
					</xs:all>
					<xs:attribute name="is.readable" type="xs:boolean" default="true"/>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="ping">
		<xs:all>
			<xs:element name="ip" type="xs:string"/>
			<xs:element name="mac" type="xs:string"/>
		</xs:all>
	</xs:complexType>
	<xs:simpleType name="format">
		<xs:restriction base="xs:string">
			<xs:enumeration value="%.0f"/>
			<xs:enumeration value="%.1f"/>
			<xs:enumeration value="%.2f"/>
			<xs:enumeration value="ND"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="modbus">
		<xs:all>
			<xs:element name="poller">
				<xs:complexType>
					<xs:all>
						<xs:element name="address" type="xs:int"/>
						<xs:element name="length" type="xs:short"/>
						<xs:element name="type" type="modbus.type" default="holding"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="address" type="xs:int"/>
			<xs:element name="read.value" type="modbus.read.value"/>
		</xs:all>
	</xs:complexType>
	<xs:simpleType name="modbus.type">
		<xs:restriction base="xs:anyURI">
			<xs:enumeration value="holding"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="modbus.read.value">
		<xs:restriction base="xs:anyURI">
			<xs:enumeration value="uint16"/>
			<xs:enumeration value="int32"/>
			<xs:enumeration value="uint32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="group">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="group.ref">
				<xs:complexType>
					<xs:attribute name="refid" type="xs:IDREF"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute ref="type" use="optional"/>
		<xs:attribute name="label" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="icon" type="icon" use="required"/>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="function" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="EQUALITY"/>
					<xs:enumeration value="AND"/>
					<xs:enumeration value="OR"/>
					<xs:enumeration value="NAND"/>
					<xs:enumeration value="NOR"/>
					<xs:enumeration value="SUM"/>
					<xs:enumeration value="AVG"/>
					<xs:enumeration value="MIN"/>
					<xs:enumeration value="MAX"/>
					<xs:enumeration value="COUNT"/>
					<xs:enumeration value="LATEST"/>
					<xs:enumeration value="EARLIEST"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="groups">
		<xs:sequence>
			<xs:element name="group" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="group"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="alexa">
		<xs:attribute name="inverted" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="true"/>
					<xs:enumeration value="false"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="primaryControl" type="xs:string" use="optional"/>
		<xs:attribute name="capabilityNames" type="xs:string" use="optional"/>
		<xs:attribute name="supportedCommands" type="xs:string" use="optional"/>
		<xs:attribute name="supportedRange" type="xs:string" use="optional"/>
		<xs:attribute name="unitOfMeasure" type="xs:string" use="optional"/>
		<xs:attribute name="actionMappings" type="xs:string" use="optional"/>
		<xs:attribute name="stateMappings" type="xs:string" use="optional"/>
		<xs:attribute name="alexa" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="knx.configuration">
		<xs:complexType>
			<xs:all>
				<xs:element name="bridge">
					<xs:complexType>
						<xs:attribute name="type" type="xs:string" default="TUNNEL"/>
						<xs:attribute name="ip.address" type="xs:string"/>
						<xs:attribute name="port.number" type="xs:string" default="3671"/>
						<xs:attribute name="local.ip" type="xs:string"/>
						<xs:attribute name="reading.pause" type="xs:short" default="50"/>
						<xs:attribute name="response.timeout" type="xs:short" default="10"/>
						<xs:attribute name="read.retries.limit" type="xs:short" default="3"/>
						<xs:attribute name="auto.reconnect.period" type="xs:short" default="60"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="tunnel">
					<xs:complexType>
						<xs:attribute name="address" type="xs:string"/>
						<xs:attribute name="fetch" type="xs:boolean" default="true"/>
						<xs:attribute name="ping.interval" type="xs:short" default="300"/>
						<xs:attribute name="read.interval" type="xs:short" default="3600"/>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="ical.configuration">
		<xs:complexType>
			<xs:all>
				<xs:element name="bridge">
					<xs:complexType>
						<xs:attribute name="url" type="xs:string" use="required"/>
						<xs:attribute name="refreshTime" type="xs:short" use="required"/>
						<xs:attribute name="username" type="xs:string" use="required"/>
						<xs:attribute name="password" type="xs:string" use="required"/>
						<xs:attribute name="maxSize" type="xs:short" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="ical">
		<xs:complexType>
			<xs:attribute name="maxEvents" type="xs:short" use="required"/>
			<xs:attribute name="refreshTime" type="xs:short" use="required"/>
			<xs:attribute name="datetimeUnit" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:anyURI">
						<xs:enumeration value="MINUTE"/>
						<xs:enumeration value="HOUR"/>
						<xs:enumeration value="DAY"/>
						<xs:enumeration value="WEEK"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="datetimeStart" type="xs:string" use="required"/>
			<xs:attribute name="datetimeEnd" type="xs:string" use="required"/>
			<xs:attribute name="textEventField" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:anyURI">
						<xs:pattern value="SUMMARY"/>
						<xs:pattern value="DESCRIPTION"/>
						<xs:pattern value="COMMENT"/>
						<xs:pattern value="CONTACT"/>
						<xs:pattern value="LOCATION"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="textEventValue" type="xs:string" use="required"/>
			<xs:attribute name="textValueType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:anyURI">
						<xs:enumeration value="TEXT"/>
						<xs:enumeration value="REGEX"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="device.specification">
		<xs:restriction base="xs:anyURI">
			<xs:enumeration value="SteinelTruePräsenz"/>
			<xs:enumeration value="RolladenMDTKNX"/>
			<xs:enumeration value="ICALBinding"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== masterofeye2021/xml2OH/SmartHomeConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2024 rel. 2 sp1 (x64) (http://www.altova.com)-->
<openhab xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SmartHomeDefinitionV2.xsd">
	<devices>
		<device device.area="WOZ" device.function="SHUTTER" device.comm.type="KNX" device.label="Rollladen Nordfenster" device.name="Rolllanden Nordfenster">
			<channel format="ND" unit="ND" access="RW" icon="fa-blinds" enable="true" persistence="false" label="Toggle Rollladen Nordfenster" type="Rollershutter" name="Auf/">
				<link>String</link>
				<connection>
					<knx>
						<add1>
							<main>8</main>
							<middle>2</middle>
							<sub>0</sub>
						</add1>
						<add2>
							<main>8</main>
							<middle>2</middle>
							<sub>1</sub>
						</add2>
						<add3>
							<main>8</main>
							<middle>2</middle>
							<sub>4</sub>
						</add3>
					</knx>
				</connection>
				<groups>
					<group refid="Shutter"></group>
					<group refid="ShutterUpDown"></group>
				</groups>
				<alexa 
				supportedRange="0:100:1"
				alexa="Blind.RangeValue"									 supportedCommands="UP=@Value.Up:@Value.Open,DOWN=@Value.Down:@Value.Close,STOP=@Value.Stop"
				actionMappings="Close=DOWN,Open=UP,Lower=DOWN,Raise=UP,Stop=STOP" 	
				unitOfMeasure="Percent"
				stateMappings="Closed=100,Open=0:99"></alexa>
			</channel>
			<channel format="ND" unit="ND" access="RW" icon="fa-octagon" enable="true" persistence="false" label="Rollladen Nordfenster Stop" type="Switch" name="Stop">
				<link>String</link>
				<connection>
					<knx>
						<add1>
							<main>8</main>
							<middle>2</middle>
							<sub>1</sub>
						</add1>
						<add2>
							<main>4096</main>
							<middle>4096</middle>
							<sub>4096</sub>
						</add2>
						<add3>
							<main>4096</main>
							<middle>4096</middle>
							<sub>4096</sub>
						</add3>
					</knx>
				</connection>
				<groups>
					<group refid="Shutter"></group>
				</groups>
				<alexa></alexa>
			</channel>
			<channel format="ND" unit="ND" access="RW" icon="fa-blinds" enable="true" persistence="false" label="Rollladen Nordfenster Aktuelle Richtung" type="Switch" name="Aktuelle Richtung">
				<link>String</link>
				<connection>
					<knx>
						<add1>
							<main>8</main>
							<middle>2</middle>
							<sub>1</sub>
						</add1>
						<add2>
							<main>4096</main>
							<middle>4096</middle>
							<sub>4096</sub>
						</add2>
						<add3>
							<main>4096</main>
							<middle>4096</middle>
							<sub>4096</sub>
						</add3>
					</knx>
				</connection>
				<groups>
					<group refid="Shutter"></group>
				</groups>
				<alexa></alexa>
			</channel>
		</device>
	</devices>
	<groups>
		<group type="Rollershutter" label="Rollladen" icon="fa-blinds" name="Shutter" id="Shutter"/>
		<group type="Rollershutter" label="Rollladen" icon="fa-blinds" name="ShutterUpDown" id="ShutterUpDown"/></groups>
</openhab>
